[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = "plugin kitty-shell -- shell"
desc = "Open a Kitty shell here"

[[mgr.prepend_keymap]]
on   = ":"
for  = "unix"
run  = "plugin kitty-shell -- command"
desc = "Run a command in a new Kitty window"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "z"
run  = "plugin zoxide"
desc = "Zoxide jump"

[[mgr.prepend_keymap]]
on   = "<C-t>"
run  = "plugin fzf"
desc = "FZF search"
