[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = '''shell --block -- bash -c 'if [[ -n $1 ]]; then printf %%s "$1" | wl-copy; fi; export YAZI_SUBSHELL=1; exec bash' _ %h'''
desc = "Copy hovered path and open Bash"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "z"
run  = "plugin zoxide"
desc = "Zoxide jump"

[[mgr.prepend_keymap]]
on   = "<C-t>"
run  = "plugin fzf"
desc = "FZF search"
