# how to find device name?
# cat /proc/bus/input/devices
[Device]
Name="LEKU NUT65 Keyboard"
Name="LEKU NUT65"
Name="CZMAO Swagkeys Eave"
Name="CZMAO Swagkeys Eave Keyboard"
Name="hfd.cn USB DEVICE" # QK60

Name="LEKU NUT65 2.4G Wireless Keyboard"
Name="QK60 2.4G"
Name="USB Dongle"

Name="AT Translated Set 2 keyboard" # Laptop


[Remap]
KEY_GRAVE=KEY_ESC 
KEY_LEFTCTRL=KEY_LEFTALT
KEY_CAPSLOCK=KEY_LEFTCTRL
KEY_LEFTALT=KEY_LEFTMETA
KEY_RIGHTALT=KEY_HANGEUL

[Hyper]
HYPER1=KEY_SPACE

[Bindings]
KEY_1=KEY_F1
KEY_2=KEY_F2
KEY_3=KEY_F3
KEY_4=KEY_F4
KEY_5=KEY_F5
KEY_6=KEY_F6
KEY_7=KEY_F7
KEY_8=KEY_F8
KEY_9=KEY_F9
KEY_0=KEY_F10
KEY_MINUS=KEY_F11
KEY_EQUAL=KEY_F12
KEY_P=KEY_PAGEUP
KEY_N=KEY_PAGEDOWN
KEY_C=KEY_LEFTCTRL
KEY_S=KEY_LEFTSHIFT
KEY_A=KEY_LEFTALT
KEY_W=KEY_LEFTMETA
KEY_K=KEY_UP
KEY_H=KEY_LEFT
KEY_J=KEY_DOWN
KEY_L=KEY_RIGHT
KEY_U=KEY_HOME
KEY_I=KEY_END
KEY_GRAVE=KEY_GRAVE
# KEY_ESC=KEY_GRAVE
KEY_TAB=KEY_SPACE
KEY_BACKSPACE=KEY_DELETE
KEY_BACKSLASH=KEY_GRAVE

# KEY_E=KEY_LEFTMETA,KEY_PAGEUP
# KEY_R=KEY_LEFTMETA,KEY_PAGEDOWN
#
# KEY_Q=KEY_LEFTMETA,KEY_1
# KEY_T=KEY_LEFTMETA,KEY_2
# KEY_D=KEY_LEFTMETA,KEY_3
# KEY_F=KEY_LEFTMETA,KEY_4
# KEY_G=KEY_LEFTMETA,KEY_5
# KEY_Z=KEY_LEFTMETA,KEY_6
# KEY_X=KEY_LEFTMETA,KEY_7
# KEY_V=KEY_LEFTMETA,KEY_8

KEY_LEFTBRACE=KEY_VOLUMEDOWN
KEY_RIGHTBRACE=KEY_VOLUMEUP
KEY_COMMA=KEY_BRIGHTNESSDOWN
KEY_DOT=KEY_BRIGHTNESSUP

KEY_SEMICOLON=BTN_LEFT
KEY_APOSTROPHE=BTN_RIGHT

KEY_M=KEY_HANGEUL
# KEY_M=KEY_RIGHTCTRL,KEY_RIGHTALT # rightctrl is for local, rightalt is for remmina
KEY_SLASH=KEY_PRINT

KEY_O=KEY_PLAYPAUSE

# B Y O DOT
